// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalMedia.Data;

#nullable disable

namespace PersonalMedia.Data.Migrations
{
    [DbContext(typeof(PersonalMediaDbContext))]
    [Migration("20251202031149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalMedia.Core.Entities.BasePersonImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureStorageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("BasePersonImages");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.GenerationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Category");

                    b.ToTable("GenerationParameters");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.GenerationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailySetsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("ImagesPerSetMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("ImagesPerSetMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("LastGenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxRetryAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("ModestyLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Family Friendly");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GenerationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailySetsCount = 5,
                            ImagesPerSetMax = 5,
                            ImagesPerSetMin = 3,
                            LastGenerationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxRetryAttempts = 3,
                            ModestyLevel = "Family Friendly",
                            ModifiedDate = new DateTime(2025, 12, 2, 3, 11, 49, 153, DateTimeKind.Utc).AddTicks(7770)
                        });
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureStorageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BasePersonImageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("GenerationCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerationPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("GenerationStartedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenerationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MediaSetId")
                        .HasColumnType("int");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BasePersonImageId");

                    b.HasIndex("MediaSetId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "ReactionType");

                    b.ToTable("MediaReactions");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("MediaSets");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.ParameterOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsActive");

                    b.ToTable("ParameterOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            IsActive = true,
                            Value = "Beach",
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            IsActive = true,
                            Value = "Mountain",
                            Weight = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            IsActive = true,
                            Value = "City",
                            Weight = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            IsActive = true,
                            Value = "Forest",
                            Weight = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            IsActive = true,
                            Value = "Park",
                            Weight = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            IsActive = true,
                            Value = "Happy",
                            Weight = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            IsActive = true,
                            Value = "Peaceful",
                            Weight = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            IsActive = true,
                            Value = "Excited",
                            Weight = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            IsActive = true,
                            Value = "Contemplative",
                            Weight = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            IsActive = true,
                            Value = "Reading",
                            Weight = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            IsActive = true,
                            Value = "Walking",
                            Weight = 1
                        },
                        new
                        {
                            Id = 12,
                            Category = 3,
                            IsActive = true,
                            Value = "Picnic",
                            Weight = 1
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            IsActive = true,
                            Value = "Photography",
                            Weight = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            IsActive = true,
                            Value = "Relaxing",
                            Weight = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = 4,
                            IsActive = true,
                            Value = "Casual",
                            Weight = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = 4,
                            IsActive = true,
                            Value = "Athletic",
                            Weight = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = 4,
                            IsActive = true,
                            Value = "Smart Casual",
                            Weight = 1
                        },
                        new
                        {
                            Id = 18,
                            Category = 5,
                            IsActive = true,
                            Value = "Morning",
                            Weight = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = 5,
                            IsActive = true,
                            Value = "Afternoon",
                            Weight = 1
                        },
                        new
                        {
                            Id = 20,
                            Category = 5,
                            IsActive = true,
                            Value = "Evening",
                            Weight = 1
                        },
                        new
                        {
                            Id = 21,
                            Category = 5,
                            IsActive = true,
                            Value = "Golden Hour",
                            Weight = 1
                        },
                        new
                        {
                            Id = 22,
                            Category = 6,
                            IsActive = true,
                            Value = "Sunny",
                            Weight = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = 6,
                            IsActive = true,
                            Value = "Cloudy",
                            Weight = 1
                        },
                        new
                        {
                            Id = 24,
                            Category = 6,
                            IsActive = true,
                            Value = "Partly Cloudy",
                            Weight = 1
                        },
                        new
                        {
                            Id = 25,
                            Category = 7,
                            IsActive = true,
                            Value = "Photorealistic",
                            Weight = 1
                        },
                        new
                        {
                            Id = 26,
                            Category = 7,
                            IsActive = true,
                            Value = "Cinematic",
                            Weight = 1
                        },
                        new
                        {
                            Id = 27,
                            Category = 7,
                            IsActive = true,
                            Value = "Portrait",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.GenerationParameter", b =>
                {
                    b.HasOne("PersonalMedia.Core.Entities.MediaItem", "MediaItem")
                        .WithMany("GenerationParameters")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("PersonalMedia.Core.Entities.BasePersonImage", "BasePersonImage")
                        .WithMany("MediaItems")
                        .HasForeignKey("BasePersonImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalMedia.Core.Entities.MediaSet", "MediaSet")
                        .WithMany("MediaItems")
                        .HasForeignKey("MediaSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePersonImage");

                    b.Navigation("MediaSet");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaReaction", b =>
                {
                    b.HasOne("PersonalMedia.Core.Entities.MediaItem", "MediaItem")
                        .WithMany("Reactions")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.BasePersonImage", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaItem", b =>
                {
                    b.Navigation("GenerationParameters");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("PersonalMedia.Core.Entities.MediaSet", b =>
                {
                    b.Navigation("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
